version: "3.6"
services:
  jupyterlab:
    image: andreper/jupyterlab:3.0.0-spark-3.0.0
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./pak:/opt/workspace/     
  spark-master:
    image: andreper/spark-master:3.0.0
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./pak:/opt/workspace/
  spark-worker-1:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=3g
    ports:
      - 8082:8082
    volumes:
      - ./pak:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=3g
    ports:
      - 8083:8082
    volumes:
      - ./pak:/opt/workspace
    depends_on:
      - spark-master
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
     - "/Test-Projet/DataBase"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    volumes:
    - "/Test-Projet/DataBase"
    depends_on:
    - mongo
    ports:
    - 8081:8081
    

